
name: Build / Release / Benchmark

# Build on each commit
# Gasmodel and release must be manually selected.
on:

  schedule:
    - cron: '36 4 * * *'

  workflow_dispatch:
    inputs:

      release:
          description: "Create a github release (Only Draft)"
          type: boolean
          required: true
          default: false

      commit_sha:
        description: "Commit to build.. Empty to build the tip"
        type: string
        required: false

      version_suffix:
        description: "Optional Suffix for the vesion number (eg beta)"
        type: string
        required: false
        default: ""


  push:
    paths:
    - '**'
    - '!.github/**'
    - '.github/workflows/applications.yml'

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ["9.14.1"]
        cabal: ["3.16"]
        os: ["ubuntu-22.04", "ubuntu-24.04"]
        freeze: ["true", "false"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
          ref: ${{ inputs.commit_sha || github.sha }}

    # Haskell Setup
    - name: Set permissions for .ghcup (ubuntu)
      if: startsWith(matrix.os, 'ubuntu-')
      run: sudo chown -R $USER /usr/local/.ghcup
    - name: Install GHC and Cabal
      uses: haskell-actions/setup@v2
      with:
         ghc-version: ${{ matrix.ghc }}
         cabal-version: ${{ matrix.cabal }}

    - name: Confirm GHC and Cabal installation
      run: |
        ghc --version
        cabal --version


    # Project Setup
    - name: Create cabal.project.local
      shell: bash
      run: |
        cat > cabal.project.local <<EOF
        documentation: False
        package chainweb-mining-client
          tests: True
          benchmarks: True
          documentation: False
          optimization: 2
        EOF

    - name: Print cabal.project.local
      shell: bash
      run: cat cabal.project.local

    # Build
    - name: Update package database
      shell: bash
      run: cabal update

    - name: Remove freeze file
      if: ${{ matrix.freeze == 'false' }}
      run : |
        rm -rf cabal.project.freeze

    - name: Configure build / and freeze
      run: |
        cabal build --dry-run
        cabal freeze

    - name: Generate cache key
      id: cache-key
      run: |
        grep -v '^index-state:' cabal.project.freeze > freeze-deps-only
        FREEZE_HASH=$(shasum freeze-deps-only | cut -d' ' -f1)
        echo "freeze-hash=$FREEZE_HASH" >> $GITHUB_OUTPUT
        rm freeze-deps-only

    - name: Restore Cabal store
      id: restore-cabal
      uses: actions/cache/restore@v5
      with:
        path: ~/.cabal/store
        key: cabal-${{ matrix.os }}-${{ matrix.ghc }}-${{ steps.cache-key.outputs.freeze-hash }}
        restore-keys: |
          cabal-${{ matrix.os }}-${{ matrix.ghc }}

    - name: Display outdated packages
      run: cabal outdated

    - name: Build dependencies
      if: steps.restore-cabal.outputs.cache-hit != 'true'
      shell: bash
      run: cabal build --only-dependencies

    - name: Cache Cabal store if necessary
      if: steps.restore-cabal.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: ~/.cabal/store
        key: cabal-${{ matrix.os }}-${{ matrix.ghc }}-${{ steps.cache-key.outputs.freeze-hash }}

    - name: Build
      shell: bash
      run: cabal build

    - name: Test
      shell: bash
      run: cabal run test:tests

    - name: Verify Binary Linking
      shell: bash
      run: cabal run chainweb-mining-client -- --long-info

    # Publish Artifacts
    - name: Prepare artifacts
      shell: bash
      run: |
        OUTPUT_DIR=artifacts/chainweb-mining-client
        mkdir -p $OUTPUT_DIR
        cp $(cabal list-bin chainweb-mining-client) $OUTPUT_DIR
        cp CHANGELOG.md $OUTPUT_DIR
        cp README.md $OUTPUT_DIR
        cp LICENSE $OUTPUT_DIR

        cd $OUTPUT_DIR
        strip chainweb-mining-client || true
        ./chainweb-mining-client --long-info > BUILD_INFO
        ./chainweb-mining-client --print-config > config.example.yaml

    - name: Publish applications
      uses: actions/upload-artifact@v7
      with:
        name: chainweb-mining-client.ghc${{ matrix.ghc }}.${{ matrix.os }}.${{ matrix.freeze }}
        path: artifacts/chainweb-mining-client



  release:

    runs-on: "ubuntu-latest"
    needs: build
    if: inputs.release == true

    env:
      GHC_FOR_RELEASE: "9.14.1"
      OS_TO_RELEASE: "ubuntu-22.04 ubuntu-24.04"
      MAIN_LINUX_VERSION: "ubuntu-24.04"

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.commit_sha || github.sha }}

      - name: Download artifacts
        uses : actions/download-artifact@v8
        with:
          pattern: chainweb-mining-client.ghc${{ env.GHC_FOR_RELEASE }}.*.true
          path: to_release/

      - name: List directory
        shell: bash
        run: ls -lR to_release

      - name: Retrieve version
        id: get_version
        shell: bash
        run: |
         BIN=to_release/chainweb-mining-client.ghc${{ env.GHC_FOR_RELEASE }}.${{ env.MAIN_LINUX_VERSION }}.true/chainweb-mining-client
          chmod a+x "$BIN"
          VERSION=$($BIN --info | sed -nE 's/^chainweb-mining-client-([0-9.]+).*/\1/p')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Prepare releases
        id: prepare
        shell: bash
        run: |
          mkdir -p releases_archives

          for o in $OS_TO_RELEASE
          do FILENAME=chainweb-mining-client-${{ steps.get_version.outputs.version }}-${GITHUB_SHA::4}-$o.tar.gz
             SRC_DIR=to_release/chainweb-mining-client.ghc${{ env.GHC_FOR_RELEASE }}.$o.true
             ARCHIVE_DIR="chainweb-mining-client-${{ steps.get_version.outputs.version }}"
             chmod a+x $SRC_DIR/chainweb-mining-client


             mkdir -p "$ARCHIVE_DIR"
             cp -a "$SRC_DIR"/. "$ARCHIVE_DIR"/

             tar czf "$GITHUB_WORKSPACE/releases_archives/$FILENAME" "$ARCHIVE_DIR"
             rm -rf "$ARCHIVE_DIR"
          done

      - name: List directory
        shell: bash
        run: ls -lR releases_archives

      - name: Generate release
        uses: ncipollo/release-action@v1

        with:
          bodyFile: .github/RELEASE.md
          artifacts: releases_archives/*
          commit: ${{ inputs.commit_sha || github.sha }}
          name: Chainweb Mining Client v${{ steps.get_version.outputs.version }}
          tag: ${{ steps.get_version.outputs.version }}
          token: ${{ secrets.GH_PAT }}
          prerelease: true
          omitBodyDuringUpdate: true
          skipIfReleaseExists: false
          draft: false
          generateReleaseNotes: true
          allowUpdates: true
          replacesArtifacts: true
          updateOnlyUnreleased: true
